plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: stux
description: Mstdn.Social Hub is an informational site tied to Mstdn, the largest FOSS focussed Mastodon instance on the fediverse.
lang: en
locale: en_GB
url: "https://hub.mstdn.social"
baseurl: ""
permalink: :title

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
