plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: stux
description: This is an informational site tied to Mastodon.Coffee social media network.
lang: en
locale: en_GB
url: "https://about.mastodon.coffee"
baseurl: ""
permalink: :title

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
